stages:
  data_prep:
    desc: Prepara datasets (train/valid/test) desde el CSV crudo
    cmd: python src\data_prep.py --input data\raw\telco_churn.csv --outdir data\processed --seed 42 --test-size 0.2 --val-size 0.1
    deps:
      - src/data_prep.py
      - data/raw/telco_churn.csv
    outs:
      - data/processed

  train:
    desc: Entrena el modelo de churn con los datos procesados
    cmd: python src\train.py --train data\processed\train.csv --valid data\processed\valid.csv --out-model models\model.joblib --metrics metrics.json --params params.yaml
    deps:
      - src/train.py
      - data/processed/train.csv
      - data/processed/valid.csv
      - params.yaml
    params:
      - train.C
      - train.max_iter
      - train.seed
    outs:
      - models/model.joblib
    metrics:
      - metrics.json
