stages:
  data_prep:
    cmd: python src\data_prep.py --input data\raw\telco_churn.csv --outdir 
      data\processed --seed 42 --test-size 0.2 --val-size 0.1
    deps:
    - data\raw\telco_churn.csv
    - src\data_prep.py
    outs:
    - data\processed
  train:
    cmd: python src\train.py --train data\processed\train.csv --valid 
      data\processed\valid.csv --out-model models\model.joblib --metrics 
      metrics.json --C 1.0 --max-iter 1000 --seed 42
    deps:
    - data\processed\train.csv
    - data\processed\valid.csv
    - src\train.py
    outs:
    - models\model.joblib
    metrics:
    - metrics.json:
        cache: false
