stages:
  data_prep:
    desc: Prepara datasets (train/valid/test) desde el CSV crudo
    cmd: python src\data_prep.py --input data\raw\telco_churn.csv --outdir data\processed --seed 42 --test-size 0.2 --val-size 0.1
    deps:
      - src/data_prep.py
      - data/raw/telco_churn.csv
    outs:
      - data/processed

  feature_eng:
    desc: Feature engineering (genera train_fe/valid_fe/test_fe)
    cmd: python src\feature_eng.py --train-in data\processed\train.csv --valid-in data\processed\valid.csv --test-in data\processed\test.csv --train-out data\features\train_fe.csv --valid-out data\features\valid_fe.csv --test-out data\features\test_fe.csv
    deps:
      - src/feature_eng.py
      - data/processed/train.csv
      - data/processed/valid.csv
      - data/processed/test.csv
    outs:
      - data/features/train_fe.csv
      - data/features/valid_fe.csv
      - data/features/test_fe.csv

  tune:
    desc: Tuning de Logistic Regression; guarda best_params y métricas de tuning
    cmd: python src\tune.py --train data\processed\train.csv --valid data\processed\valid.csv --params params.yaml --best-out artifacts\best_params.json --metrics-out metrics_tune.json
    deps:
      - src/tune.py
      - data/processed/train.csv
      - data/processed/valid.csv
    params:
      - train.C
      - train.max_iter
      - train.seed
    outs:
      - artifacts/best_params.json
    metrics:
      - metrics_tune.json

  train:
    desc: Entrena Logistic Regression con best_params y registra en MLflow
    cmd: python src\train.py --train data\processed\train.csv --valid data\processed\valid.csv --out-model models\model.joblib --metrics metrics.json --best-params artifacts\best_params.json --params params.yaml
    deps:
      - src/train.py
      - data/processed/train.csv
      - data/processed/valid.csv
      - artifacts/best_params.json
    params:
      - train.C
      - train.max_iter
      - train.seed
    outs:
      - models/model.joblib
    metrics:
      - metrics.json

  threshold:
    desc: Busca umbral óptimo en VALID para el modelo base
    cmd: python src\threshold.py --valid data\processed\valid.csv --model models\model.joblib --out-json artifacts\best_threshold.json --metrics-out metrics_threshold.json --roc-out reports\roc_curve.png --pr-out reports\pr_curve.png
    deps:
      - src/threshold.py
      - data/processed/valid.csv
      - models/model.joblib
    outs:
      - artifacts/best_threshold.json
      - reports/roc_curve.png
      - reports/pr_curve.png
    metrics:
      - metrics_threshold.json

  evaluate_test:
    desc: Evalúa el modelo base en TEST
    cmd: python src\evaluate.py --test data\processed\test.csv --model models\model.joblib --metrics-out metrics_test.json
    deps:
      - src/evaluate.py
      - data/processed/test.csv
      - models/model.joblib
    metrics:
      - metrics_test.json

  tune_rf:
    desc: Tuning de RandomForest; guarda best_params_rf y métricas
    cmd: python src\tune_rf.py --train data\processed\train.csv --valid data\processed\valid.csv --params params.yaml --best-out artifacts\best_params_rf.json --metrics-out metrics_tune_rf.json
    deps:
      - src/tune_rf.py
      - data/processed/train.csv
      - data/processed/valid.csv
    outs:
      - artifacts/best_params_rf.json
      - metrics_tune_rf.json

  train_rf:
    desc: Entrena RandomForest con best_params_rf y registra en MLflow
    cmd: python src\train_rf.py --train data\processed\train.csv --valid data\processed\valid.csv --out-model models\model_rf.joblib --metrics metrics_rf.json --best-params artifacts\best_params_rf.json --params params.yaml
    deps:
      - src/train_rf.py
      - data/processed/train.csv
      - data/processed/valid.csv
      - artifacts/best_params_rf.json
    params:
      - train.seed
    outs:
      - models/model_rf.joblib
    metrics:
      - metrics_rf.json

  evaluate_test_rf:
    desc: Evalúa RandomForest en TEST
    cmd: python src\evaluate.py --test data\processed\test.csv --model models\model_rf.joblib --metrics-out metrics_test_rf.json
    deps:
      - src/evaluate.py
      - data/processed/test.csv
      - models/model_rf.joblib
    metrics:
      - metrics_test_rf.json

  tune_xgb:
    desc: Tuning de XGBoost; guarda best_params_xgb y métricas
    cmd: python src\tune_xgb.py --train data\processed\train.csv --valid data\processed\valid.csv --params params.yaml --best-out artifacts\best_params_xgb.json --metrics-out metrics_tune_xgb.json
    deps:
      - src/tune_xgb.py
      - data/processed/train.csv
      - data/processed/valid.csv
    outs:
      - artifacts/best_params_xgb.json
    metrics:
      - metrics_tune_xgb.json

  train_xgb:
    desc: Entrena XGBoost con best_params_xgb y registra en MLflow
    cmd: python src\train_xgb.py --train data\processed\train.csv --valid data\processed\valid.csv --out-model models\model_xgb.joblib --metrics metrics_xgb.json --best-params artifacts\best_params_xgb.json --params params.yaml
    deps:
      - src/train_xgb.py
      - data/processed/train.csv
      - data/processed/valid.csv
      - artifacts/best_params_xgb.json
    params:
      - train.seed
    outs:
      - models/model_xgb.joblib
    metrics:
      - metrics_xgb.json

  threshold_xgb:
    desc: Busca umbral óptimo en VALID para XGBoost
    cmd: python src\threshold.py --valid data\processed\valid.csv --model models\model_xgb.joblib --out-json artifacts\best_threshold_xgb.json --metrics-out metrics_threshold_xgb.json --roc-out reports\roc_curve_xgb.png --pr-out reports\pr_curve_xgb.png
    deps:
      - src/threshold.py
      - data/processed/valid.csv
      - models/model_xgb.joblib
    outs:
      - artifacts/best_threshold_xgb.json
      - reports/roc_curve_xgb.png
      - reports/pr_curve_xgb.png
    metrics:
      - metrics_threshold_xgb.json

  train_fe:
    desc: Entrena Logistic Regression usando datasets con FE
    cmd: python src\train.py --train data\features\train_fe.csv --valid data\features\valid_fe.csv --out-model models\model_fe.joblib --metrics metrics_fe.json --best-params artifacts\best_params.json --params params.yaml
    deps:
      - src/train.py
      - data/features/train_fe.csv
      - data/features/valid_fe.csv
      - artifacts/best_params.json
    params:
      - train.C
      - train.max_iter
      - train.seed
    outs:
      - models/model_fe.joblib
    metrics:
      - metrics_fe.json

  evaluate_test_fe:
    desc: Evalúa el modelo FE en TEST (usa test_fe)
    cmd: python src\evaluate.py --test data\features\test_fe.csv --model models\model_fe.joblib --metrics-out metrics_test_fe.json
    deps:
      - src/evaluate.py
      - data/features/test_fe.csv
      - models/model_fe.joblib
    metrics:
      - metrics_test_fe.json

  select_register:
    desc: Selecciona champion a partir de métricas y registra/actualiza en MLflow; escribe selection.json
    cmd: python scripts\select_and_register.py --mlflow-uri http://127.0.0.1:5001 --write-out artifacts\selection.json
    deps:
      - scripts/select_and_register.py
      - metrics_test.json
      - metrics_test_rf.json
      - metrics_test_xgb.json
      - metrics_test_fe.json
    outs:
      - artifacts/selection.json

  predict_champion:
    desc: Descarga el champion del Model Registry y predice sobre TEST
    cmd: python scripts\predict_champion.py --test data\processed\test.csv --out predictions\preds_test_champion.csv --mlflow-uri http://127.0.0.1:5001
    deps:
      - scripts/predict_champion.py
      - artifacts/selection.json
      - data/processed/test.csv
    outs:
      - predictions/preds_test_champion.csv

  report_benchmark:
    desc: Reporte comparativo de F1 (md + figura) a partir de métricas de TEST
    cmd: python src\report_benchmark.py --sources metrics_test.json metrics_test_rf.json metrics_test_xgb.json metrics_test_fe.json --out-md reports/benchmark.md --out-fig reports/f1_bench.png
    deps:
      - src/report_benchmark.py
      - metrics_test.json
      - metrics_test_rf.json
      - metrics_test_xgb.json
      - metrics_test_fe.json
    outs:
      - reports/benchmark.md
      - reports/f1_bench.png

  alias_champion:
    desc: Aplica alias 'champion' al modelo ganador en MLflow (idempotente)
    cmd: python scripts\alias_champion.py --mlflow-uri http://127.0.0.1:5001 --selection artifacts\selection.json --alias champion --write-out artifacts\aliases_applied.json
    deps:
      - scripts/alias_champion.py
      - artifacts/selection.json
    outs:
      - artifacts/aliases_applied.json