stages:
  data_prep:
    cmd: python src/data_prep.py --input data/raw/telco_churn.csv --outdir data/processed --seed 42 --test-size 0.2 --val-size 0.1
    deps:
      - src/data_prep.py
      - data/raw/telco_churn.csv
    outs:
      - data/processed/train.csv
      - data/processed/valid.csv
      - data/processed/test.csv
      - data/processed/features.json
