train:
  C: 1.0
  max_iter: 1000
  seed: 42

tune:
  C_grid: [0.01, 0.1, 1.0, 10.0]
  max_iter_grid: [1000]
  cv: 1   # 1 = holdout (usa valid.csv). Podés subir a 5 para CV.

train_rf:
  n_estimators: 300
  max_depth: 5
  min_samples_split: 5
  seed: 42

tune_rf:
  n_estimators: [200, 300, 500]
  max_depth: [5, 7, 9]
  min_samples_split: [2, 5]
  seed: 42

train_xgb:
  n_estimators: 300
  max_depth: 5
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  reg_lambda: 1.0
  random_state: 42

tune_xgb:
  n_estimators: [200, 300]
  max_depth: [3, 5, 7]
  learning_rate: [0.1, 0.05]
  subsample: [0.8, 1.0]
  colsample_bytree: [0.8, 1.0]
  reg_lambda: [1.0, 2.0]
  random_state: 42
