train:
  C: 1.0
  max_iter: 1000
  seed: 42
  threshold: 0.5

tune:
  C_grid: [0.01, 0.1, 1.0, 3.0, 10.0]
  cv: 5
  scoring: f1
  max_iter: 1000

train_rf:
  n_estimators: 200
  max_depth: null
  min_samples_split: 2
  seed: 42

tune_rf:
  n_estimators_grid: [100, 200, 300]
  max_depth_grid: [null, 5, 10, 20]
  min_samples_split_grid: [2, 5]
  cv: 5
  scoring: f1

